name: promqlinter - A PromQL linter with k8s manifest/etc YAMLs.
author: Drumato
description: install and run promqlinter 
inputs:
  root_dir:
    description: "the target directory promqlinter checks"
    required: true 
    default: "."
  ansi_colors:
    description: "determine whether the promqlinter's reports are colored with ANSI codes"
    default: "false"
    required: false
  denied_labels:
    description: |
      the not-allowed label-matchers '<label> %PAIR% <value-pattern-regexp>' separated by comma.
      like 'job %PAIR% node_exporter,instance %PAIR% .*'
    required: false
    default: ""
outputs:
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "-c"
    - ${{ inputs.ansi_colors }}
    - "-r"
    - "-i"
    - ${{ inputs.root_dir }}
    - "--denied-labels"
    - ${{ inputs.denied_labels }}
branding:
  icon: 'git-pull-request'
  color: 'blue'
